# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

# 1. La versión es OBLIGATORIA para el validador de VS Code
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # 2. 'disable-all' debe ir dentro de 'linters' y antes de 'enable'
  disable-all: false
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
    - goconst
    - unconvert
    - prealloc
    - bodyclose
    - gocritic
    - nolintlint
    - unparam

# 3. 'linters-settings' ahora será reconocido al estar bien definido lo anterior
linters-settings:
  errcheck:
    check-type-assertions: true

  goimports:
    # Recuerda los corchetes [] para que sea un array
    local-prefixes: ["github.com/kaulinmindiola/global-ecommerce-api"]

  revive:
    rules:
      - name: exported
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
