package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/kaulinmindiola/global-ecommerce-api/internal/domain"
	"github.com/kaulinmindiola/global-ecommerce-api/internal/repository"
)

// userRepository implements repository.UserRepository using PostgreSQL.
// It is unexported intentionally — callers interact only through the interface.
type userRepository struct {
	db *pgxpool.Pool
}

// NewUserRepository creates a new PostgreSQL-backed UserRepository.
// The returned value satisfies the repository.UserRepository interface.
func NewUserRepository(db *pgxpool.Pool) repository.UserRepository {
	return &userRepository{db: db}
}

// Create inserts a new user into the database.
// The user's ID must be a valid UUID, typically generated by domain.NewUser().
func (r *userRepository) Create(ctx context.Context, user *domain.User) error {
	query := `
		INSERT INTO users (
			id, email, full_name, password_hash,
			preferred_currency_id, preferred_timezone,
			is_active, created_at, updated_at
		) VALUES (
			$1, $2, $3, $4, $5, $6, $7, $8, $9
		)`

	_, err := r.db.Exec(ctx, query,
		user.ID,
		user.Email,
		user.FullName,
		user.PasswordHash,
		user.PreferredCurrencyID,
		user.PreferredTimezone,
		user.IsActive,
		user.CreatedAt,
		user.UpdatedAt,
	)
	if err != nil {
		return fmt.Errorf("creating user: %w", mapPgError(err))
	}

	return nil
}

// GetByID fetches a single user by UUID.
// Returns domain.ErrNotFound if no row matches.
func (r *userRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	query := `
		SELECT
			id, email, full_name, password_hash,
			preferred_currency_id, preferred_timezone,
			is_active, created_at, updated_at
		FROM users
		WHERE id = $1 AND is_active = true`

	user := &domain.User{}
	err := r.db.QueryRow(ctx, query, id).Scan(
		&user.ID,
		&user.Email,
		&user.FullName,
		&user.PasswordHash,
		&user.PreferredCurrencyID,
		&user.PreferredTimezone,
		&user.IsActive,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrNotFound
		}
		return nil, fmt.Errorf("getting user by id %s: %w", id, err)
	}

	return user, nil
}

// GetByEmail fetches a single user by their unique email address.
// Returns domain.ErrNotFound if no row matches.
func (r *userRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	query := `
		SELECT
			id, email, full_name, password_hash,
			preferred_currency_id, preferred_timezone,
			is_active, created_at, updated_at
		FROM users
		WHERE email = $1 AND is_active = true`

	user := &domain.User{}
	err := r.db.QueryRow(ctx, query, email).Scan(
		&user.ID,
		&user.Email,
		&user.FullName,
		&user.PasswordHash,
		&user.PreferredCurrencyID,
		&user.PreferredTimezone,
		&user.IsActive,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrNotFound
		}
		return nil, fmt.Errorf("getting user by email %s: %w", email, err)
	}

	return user, nil
}

// Update persists changes to an existing user record.
// Only mutable fields are updated; id and created_at are immutable.
func (r *userRepository) Update(ctx context.Context, user *domain.User) error {
	query := `
		UPDATE users SET
			full_name             = $2,
			preferred_currency_id = $3,
			preferred_timezone    = $4,
			updated_at            = $5
		WHERE id = $1 AND is_active = true`

	tag, err := r.db.Exec(ctx, query,
		user.ID,
		user.FullName,
		user.PreferredCurrencyID,
		user.PreferredTimezone,
		user.UpdatedAt,
	)
	if err != nil {
		return fmt.Errorf("updating user %s: %w", user.ID, mapPgError(err))
	}

	if tag.RowsAffected() == 0 {
		return domain.ErrNotFound
	}

	return nil
}

// Delete performs a soft delete by setting is_active = false.
// The record is preserved for audit purposes; it is never physically removed.
func (r *userRepository) Delete(ctx context.Context, id uuid.UUID) error {
	query := `
		UPDATE users SET is_active = false, updated_at = NOW()
		WHERE id = $1 AND is_active = true`

	tag, err := r.db.Exec(ctx, query, id)
	if err != nil {
		return fmt.Errorf("deleting user %s: %w", id, err)
	}

	if tag.RowsAffected() == 0 {
		return domain.ErrNotFound
	}

	return nil
}

// List returns a paginated slice of active users with a total count.
// The total count reflects the full dataset (before pagination) for use in
// constructing pagination metadata in the service/handler layers.
func (r *userRepository) List(ctx context.Context, params repository.ListParams) ([]*domain.User, int64, error) {
	// Validate and apply safe defaults to prevent unbounded queries.
	if params.PageSize <= 0 || params.PageSize > 100 {
		params.PageSize = 20
	}
	if params.Page <= 0 {
		params.Page = 1
	}
	offset := (params.Page - 1) * params.PageSize

	// Count query — runs before the data query so we always return accurate totals.
	countQuery := `SELECT COUNT(*) FROM users WHERE is_active = true`
	var total int64
	if err := r.db.QueryRow(ctx, countQuery).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("counting users: %w", err)
	}

	// Data query with pagination.
	dataQuery := `
		SELECT
			id, email, full_name, password_hash,
			preferred_currency_id, preferred_timezone,
			is_active, created_at, updated_at
		FROM users
		WHERE is_active = true
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`

	rows, err := r.db.Query(ctx, dataQuery, params.PageSize, offset)
	if err != nil {
		return nil, 0, fmt.Errorf("listing users: %w", err)
	}
	defer rows.Close()

	users := make([]*domain.User, 0, params.PageSize)
	for rows.Next() {
		user := &domain.User{}
		if err := rows.Scan(
			&user.ID,
			&user.Email,
			&user.FullName,
			&user.PasswordHash,
			&user.PreferredCurrencyID,
			&user.PreferredTimezone,
			&user.IsActive,
			&user.CreatedAt,
			&user.UpdatedAt,
		); err != nil {
			return nil, 0, fmt.Errorf("scanning user row: %w", err)
		}
		users = append(users, user)
	}

	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("iterating user rows: %w", err)
	}

	return users, total, nil
}
